### ISSUE TITLE
JpegRecorder throws  error

### ISSUE THREAD

**Issue by emrullaharsay** [natmlx/NatCorder#10]
I recently updated 1.8.9 and I was using JpegRecorder to take screen shots in earlier version.Now I am getting _ObjectDisposedException_ error and it doesnt take screenshots.

![ss2](https://user-images.githubusercontent.com/17803517/197967871-1ec07cc3-e7ad-4ced-90a9-5a0a92035d46.png)

**Comment by olokobayusuf** [comment]
Hey @emrullaharsay , thanks for reporting this! It has been fixed in the upcoming 1.9.0 release. This version should be out before November 1st.

**Comment by olokobayusuf** [comment]
[Fixed in 1.9.0](https://github.com/natmlx/NatCorder/releases/tag/1.9.0).
