### ISSUE TITLE
High resolution `MP4Recorder` crash

### ISSUE THREAD

**Issue by mshandle** [natmlx/NatCorder#12]
Some Android devices cannot support any video resolution

`12-02 11:39:28.771  1022 31143 E MtkOmxVenc: [0xed272600] [ERROR] cannot support H.264 (1080x2460) encoder
12-02 11:39:28.771  1022 31143 E MtkOmxVenc: [0xed272600] [ERROR] cannot init encode driver`

**Comment by mshandle** [comment]
Need Get Support Resolutions。

**Comment by olokobayusuf** [comment]
NatCorder does not support reporting resolutions. Can you share the full crash logs so that we can prevent a hard-crash when this happens? As for the recording, I recommend capping your resolution to 1080p.

**Comment by olokobayusuf** [comment]
Closing as this issue is device-specific.
