### ISSUE TITLE
Cant build on Android from Unity 2022.1.23

### ISSUE THREAD

**Issue by aholla** [natmlx/NatCorder#13]
`HttpRequestException: Request headers must contain only ASCII characters.
System.Net.Http.HttpConnection.WriteStringAsync (System.String s) (at <32029b009d2e490faa5e479e9b1f8aba>:0)
System.Net.Http.HttpConnection.WriteHeadersAsync (System.Net.Http.Headers.HttpHeaders headers, System.String cookiesFromContainer) (at <32029b009d2e490faa5e479e9b1f8aba>:0)
System.Net.Http.HttpConnection.SendAsyncCore (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) (at <32029b009d2e490faa5e479e9b1f8aba>:0)
System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync (System.Net.Http.HttpConnection connection, System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) (at <32029b009d2e490faa5e479e9b1f8aba>:0)
System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) (at <32029b009d2e490faa5e479e9b1f8aba>:0)
System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) (at <32029b009d2e490faa5e479e9b1f8aba>:0)
System.Net.Http.HttpClient.FinishSendAsyncBuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) (at <32029b009d2e490faa5e479e9b1f8aba>:0)
NatML.Hub.NatMLHub.RequestNet[TRequest,TResponse] (TRequest request, System.String accessKey) (at Library/PackageCache/ai.natml.hub@1.0.15/Runtime/NatMLHub.cs:181)
NatML.Hub.NatMLHub.GetUser (System.String accessKey) (at Library/PackageCache/ai.natml.hub@1.0.15/Runtime/NatMLHub.cs:78)
Rethrow as AggregateException: One or more errors occurred. (Request headers must contain only ASCII characters.)
System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) (at <5fa84b4935964448a51c359531ad218d>:0)
System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) (at <5fa84b4935964448a51c359531ad218d>:0)
System.Threading.Tasks.Task`1[TResult].get_Result () (at <5fa84b4935964448a51c359531ad218d>:0)
NatML.Hub.Editor.HubProjectSettings.CreateSettings (System.Boolean refresh) (at Library/PackageCache/ai.natml.hub@1.0.15/Editor/HubProjectSettings.cs:46)
NatML.Hub.Editor.SettingsEmbedHelper.CreateEmbeds (UnityEditor.Build.Reporting.BuildReport report) (at Library/PackageCache/ai.natml.hub@1.0.15/Editor/SettingsEmbedHelper.cs:19)
NatML.Hub.Editor.BuildEmbedHelper`1[T].UnityEditor.Build.IPreprocessBuildWithReport.OnPreprocessBuild (UnityEditor.Build.Reporting.BuildReport report) (at Library/PackageCache/ai.natml.hub@1.0.15/Editor/BuildEmbedHelper.cs:89)
UnityEditor.Build.BuildPipelineInterfaces+<>c__DisplayClass16_0.<OnBuildPreProcess>b__1 (UnityEditor.Build.IPreprocessBuildWithReport bpp) (at /Users/bokken/build/output/unity/unity/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:437)
UnityEditor.Build.BuildPipelineInterfaces.InvokeCallbackInterfacesPair[T1,T2] (System.Collections.Generic.List`1[T] oneInterfaces, System.Action`1[T] invocationOne, System.Collections.Generic.List`1[T] twoInterfaces, System.Action`1[T] invocationTwo, System.Boolean exitOnFailure) (at /Users/bokken/build/output/unity/unity/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:403)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:189)
`

**Comment by aholla** [comment]
Issues was related to strange character in the API key.

**Comment by olokobayusuf** [comment]
Sounds good.
