### ISSUE TITLE
IOS Build error

### ISSUE THREAD

**Issue by hu1won** [natmlx/NatCorder#16]
__Hello,__

> This issue occurred while building in IOS Xcode.
> Please check the image below.
> 
> ![image](https://user-images.githubusercontent.com/71807924/211265439-dcb243dc-96cd-41d4-bc5f-a8b8209aecdb.png)
>

I judged that this error is related to __NatCorder.__
There seems to have been an error building an iOS project in Xcode. This error message displays a conflict between the NATCorder and some other components.

NAT Corder is a Unity plug-in that allows you to record video and audio from a Unity app or game. I believe the conflict may be related to version compatibility issues between some other components of the project and NATCorder.

* Why did this problem occur, and is there a way to solve this problem?

**Comment by olokobayusuf** [comment]
Only the `_NC` errors apply to NatCorder. You look like you have an outdated version of NatCorder in your project. Delete NatCorder then reimport it by [following the setup instructions](https://github.com/natmlx/NatCorder#installing-natcorder).

**Comment by hu1won** [comment]
> Only the `_NC` errors apply to NatCorder. You look like you have an outdated version of NatCorder in your project. Delete NatCorder then reimport it by [following the setup instructions](https://github.com/natmlx/NatCorder#installing-natcorder).

Thanks @olokobayusuf , I'll try and thank you for the information. It appears that the error I'm experiencing only applies to NatCorder. I will delete the outdated version of NatCorder in my project and reimport it by following the setup instructions to see if that resolves the issue. Thank you for your help.

I will try this and give you an answer again. Thank you!!!!

**Comment by olokobayusuf** [comment]
Sounds good. Closing this issue, so feel free to reopen a new issue if you face any new errors. I also recommend joining the NatML community [on Discord](https://natml.ai/community).
