### ISSUE TITLE
Big lag when recording camera

### ISSUE THREAD

**Issue by MonsieurD** [natmlx/NatCorder#17]
The camera recording is very very slow. 

When I was recording with an access key on a free plan, the recording was ok, no lag at all.
Now my client has paid the core plan, the recording is very slow. All the things I want to record are slow down. It's not usable.

Here is my recording code :
```
m_Clock = new RealtimeClock();
m_Recorder = new MP4Recorder(720, 1280, 30, AudioSettings.outputSampleRate, (int)AudioSettings.speakerMode);
 
m_CameraInput = new CameraInput(m_Recorder, m_Clock, m_Camera);

  if (m_AudioListener != null)
      m_AudioInput = new AudioInput(m_Recorder, m_Clock, m_AudioListener);
```

Can you help me ?

**Comment by MonsieurD** [comment]
![image](https://user-images.githubusercontent.com/6513285/212025418-e7268bf9-da16-4884-82c8-1552cfc57f1a.png)

**Comment by olokobayusuf** [comment]
Are you recording on Windows? If so, this happens when you specify audio settings (the sample rate and channel count) but don't actually commit any audio (i.e., when `m_AudioListener` is `null`).

**Comment by MonsieurD** [comment]
Yes that was it ! Thank you very much.

Howerer i have now another isue inside my webgl build :

NotImplementedException: The method or operation is not implemented.
  at NatML.Recorders.Internal.NatCorder.CheckStatus (NatML.Recorders.Internal.NatCorder+Status status) [0x00000] in <00000000000000000000000000000000>:0 

The record don't start ...

**Comment by olokobayusuf** [comment]
@MonsieurD I recommend opening a new issue for separate items you want to report. For the error above, you are likely trying to use a recorder that isn't supported on WebGL. WebGL only supports a small set of recorders, [see the table](https://docs.natml.ai/natcorder/preliminaries/faq#are-recorders-cross-platform).
