### ISSUE TITLE
WebGL webm record resize game view

### ISSUE THREAD

**Issue by MonsieurD** [natmlx/NatCorder#19]
When I record a video with webm recorder on webgl, the screen is resized to the (I think) target resolution of the record.

Before recording :
![image](https://user-images.githubusercontent.com/6513285/212853786-28b2a956-32fb-4087-8db2-00f25b784a66.png)
During recording :
![image](https://user-images.githubusercontent.com/6513285/212853941-d5851e2a-e4eb-422f-a722-f46017c651dc.png)
After it returns to the original resolution.

Can I avoid this behaviour ?

**Comment by olokobayusuf** [comment]
What version of Unity are you using? And can you share your recording code? This is likely a Unity bug.

**Comment by olokobayusuf** [comment]
Do you have any AR framework in your project?

**Comment by MonsieurD** [comment]
No AR framework in my project.

**Comment by olokobayusuf** [comment]
In this case it must be a bug within Unity Engine. I recommend trying out a different version of Unity, or switching to using the `ScreenInput` instead of `CameraInput`. I'm closing this issue.
