### ISSUE TITLE
AndroidJavaException on StopRecording

### ISSUE THREAD

**Issue by yosun** [natmlx/natcorder#21]
Unity 2020.3.27f1 LTS / Natcorder 1.8.3 issue occurs after recording stop / save
Video save / silent fail issue. 

````
2023/03/06 01:29:09.573 19526 19547 Error Unity AndroidJavaException: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Thread.interrupt()' on a null object reference
2023/03/06 01:29:09.573 19526 19547 Error Unity java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Thread.interrupt()' on a null object reference
2023/03/06 01:29:09.573 19526 19547 Error Unity 	at com.olokobayusuf.natmic.AudioDevice.stopRecording(AudioDevice.java:125)
2023/03/06 01:29:09.573 19526 19547 Error Unity 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
2023/03/06 01:29:09.573 19526 19547 Error Unity 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
2023/03/06 01:29:09.573 19526 19547 Error Unity 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
2023/03/06 01:29:09.573 19526 19547 Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:102)
2023/03/06 01:29:09.573 19526 19547 Error Unity 	at android.os.Looper.loopOnce(Looper.java:201)
2023/03/06 01:29:09.573 19526 19547 Error Unity 	at android.os.Looper.loop(Looper.java:288)
2023/03/06 01:29:09.573 19526 19547 Error Unity 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
2023/03/06 01:29:09.573 19526 19547 Error Unity   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
2023/03/06 01:29:09.573 19526 19547 Error Unity   at UnityEngine.AndroidJavaObject._Call (System.String methodName, System.Object[] args) [0x00000] in <00000000000000000000000000000000>:0 
2023/03/06 01:29:09.573 19526 19547 Error Unity   at NatMicCorder+<

````

**Comment by olokobayusuf** [comment]
Hey @yosun you're using far outdated software (looks like NatMic). I recommend upgrading to [the latest VideoKit](https://github.com/natmlx/videokit).

**Comment by yosun** [comment]
For a legacy project with other plugins that may break if not using Unity 2020, are there things in Natcorder that might not work in Unity 2020?

VideoKit looks cool! If all I need is screen recording (don't need TikTok effects etc), should I just stick with NatCorder?

**Comment by olokobayusuf** [comment]
> For a legacy project with other plugins that may break if not using Unity 2020, are there things in Natcorder that might not work in Unity 2020?

I think so, because NatCorder (and all our other APIs) use the latest C# features in Unity.

> VideoKit looks cool! If all I need is screen recording (don't need TikTok effects etc), should I just stick with NatCorder?

Switch to VideoKit if you can! It does everything that NatCorder and NatDevice do, and much (much) more. [See the docs](https://docs.videokit.ai/videokit/workflows/videos).
