### ISSUE TITLE
InvalidOperationException: NatCorder session token is invalid. Check your NatML access key.

### ISSUE THREAD

**Issue by stars66** [natmlx/natcorder#22]
That error occurs on WebGL. Cannot record.

**Comment by olokobayusuf** [comment]
Hey @stars66 can you share your `manifest.json` along with the full text of the error from the device browser? Also in Player Settings, what is your `Company Name` and `Product Name`? And what is your NatML Hub username?

**Comment by stars66** [comment]
Thanks for your response. I solved the issue. Problem was in Opsive plugin.

**Comment by olokobayusuf** [comment]
Sounds good!

**Comment by stars66** [comment]
One question, How can I download webm video?

**Comment by olokobayusuf** [comment]
For questions like this, I recommend asking on [our Discord community](https://www.natml.ai/community).

To answer your question, switch over to [VideoKit](https://github.com/natmlx/VideoKit), then use the [`VideoKitRecorder`](https://docs.videokit.ai/videokit/workflows/videos) component and set the `destination` setting to `CameraRoll`.
