### ISSUE TITLE
Audio plays faster than video in the recorded output

### ISSUE THREAD

**Issue by maxcelar** [natmlx/natcorder#24]
Platform: iOS
Unity Version: 2022.2.12f
Render pipeline: URP
Recorder: MP4

The rendered MP4 contains audio that is playing too fast - about twice the speed of the real time. 
I'm using:
```
recorder = new MP4Recorder(Screen.width, Screen.height, 30, 48000, 2);
 audioInput = new AudioInput(recorder, audioListener);
```

I've also tried:
```
recorder = new MP4Recorder(Screen.width, Screen.height, 30, 48000, 2);
clock = new RealtimeClock();
audioInput = new AudioInput(recorder, clock, audioListener);
```

and the result is the same. The same clock is used for getting timestamp for the CommitFrame function.

Thanks in advance for any advice.

**Comment by olokobayusuf** [comment]
If you're recording audio from Unity (i.e. using `AudioInput`), then the audio format you specify in the recorder constructor **must** match that of Unity engine. So change your code to:
```csharp
var sampleRate = AudioSettings.outputSampleRate;
var channelCount = (int)AudioSettings.speakerMode;
recorder = new MP4Recorder(Screen.width, Screen.height, 30, sampleRate, channelCount);
```

But taking a step back, I **strongly, strongly** recommend switching to [VideoKit](https://github.com/natmlx/VideoKit), so that you don't have to write code (and can avoid issues like this).

**Comment by maxcelar** [comment]
Thanks for the quick response @olokobayusuf . I will try out your solution.
We need to use custom textures since we're selectively blitting certain UI elements (eg. subtitles). 
But just for the record - does VideoKit render without UI (created in UIToolkit)?

**Comment by olokobayusuf** [comment]
> We need to use custom textures since we're selectively blitting certain UI elements (eg. subtitles).

[VideoKit supports recording from textures](https://docs.videokit.ai/videokit/api/videokitrecorder#specifying-the-recording-texture).

> But just for the record - does VideoKit render without UI (created in UIToolkit)?

If you're rendering from a game camera and don't want a UI canvas included, you can either set the canvas render mode to overlay, or create a second game camera that only sees the UI canvas (and record from the other camera that doesn't see the UI).
