### ISSUE TITLE
Linear color space support

### ISSUE THREAD

**Issue by thesanketkale** [natmlx/NatCorder#5]
Hi @olokobayusuf,

The 3D assets in the video recorded with the latest version of NatCorder (1.8.6) appear dark when compiled with linear color space on Android devices. Video recording in Linear color space was supported in the asset store version (~1.8.2) and is important for our project that has been using NatCorder since the early versions.

But since the latest cloud version, the 3D assets appear dark in the video recorded from an android device, which kind of ruins all the great performance in the cloud version.

Video recording works OK with linear color space on the iOS platform but lacks lighting data on android devices.

Unity version: 2021.1.28f1
Target Platform: Android
Mobile devices tested on: OnePlus Nord 2, Xiaomi Poco f2, Moto X4

**Comment by olokobayusuf** [comment]
Hey @thesanketkale I should note that this actually works everywhere, except when using the `GLESTextureInput`. We've added linear rendering support to the `GLESTextureInput` for NatCorder 1.8.7. Should be released later today.

**Comment by olokobayusuf** [comment]
Fixed in [1.8.7](https://github.com/natmlx/NatCorder/releases/tag/1.8.7).
