### ISSUE TITLE
Initial 1-2 seconds are missing when recording audio

### ISSUE THREAD

**Issue by emielch** [natmlx/NatCorder#6]
When recording audio, the first seconds of the video are missing. Most video players just show the same frame for the first 1-2 seconds of the video after which it does start playing. Depending on the video player that is used the audio will play from the start of the video (while the video is frozen), starts when the video also starts playing (silence for the first 1-2 seconds) or the video will actually start immediately but with the audio/video being out of sync (and with the first seconds of video after pressing record missing) . Also depending on the player, the video might get stretched/zoomed in once it starts playing (the frozen image at the start looks normal).

When not recording audio it all works fine, and the first few seconds are not missing.

This is on Android (no problems when recording in the Unity editor on Windows) with NatCorder 1.8.7 but (if I remember correctly) this has been an issue since version 1.8.3.

**Comment by olokobayusuf** [comment]
Reproduced. This bug actually causes drift in the audio, so the audio is behind the video by about 1-2 seconds.

**Comment by olokobayusuf** [comment]
Issue has been fixed for NatCorder 1.8.8! Thanks for your patience with this @emielch 😌

**Comment by emielch** [comment]
@olokobayusuf Thank you for fixing it, I'm looking forward to the release!

**Comment by olokobayusuf** [comment]
Fixed in 1.8.8.
