### ISSUE TITLE
How to set up the Access Key?

### ISSUE THREAD

**Issue by rgm-22** [natmlx/NatCorder#9]
Hi!

I'm trying to set up NatCorder following this website:

https://docs.natml.ai/natcorder/preliminaries/getting-started

I already have my Access Key, but where should I place it?

<img width="690" alt="unity" src="https://user-images.githubusercontent.com/68119614/196819494-e02c6d79-da89-47bf-827b-e384459052a3.png">

With this configuration, I'm getting:

<img width="653" alt="unity_2" src="https://user-images.githubusercontent.com/68119614/196819709-190d512b-0013-4db3-9288-388c5ae9d53e.png">

Thank you in advance!

**Comment by olokobayusuf** [comment]
Hey @rgm-22 , what version of Unity are you using? The compiler errors indicate that you might be using an older version of Unity. You'll need Unity 2021.2 or newer to use any of our APIs. Once you get past the compiler errors, there will be a "NatML" section in Project Settings where you can enter your access key.

**Comment by raulpyimagesearch** [comment]
Thank you for your answer, @olokobayusuf !

I see...I'm using Unity 2019.4, and I need to use this version.

Is there no solution?

**Comment by olokobayusuf** [comment]
Hey @rgm-22 , NatCorder (along with all of our other APIs) require Unity 2021.2. Unfortunately, there is no easy way to use Unity 2019.4 with NatCorder. Why are you not able to upgrade?

**Comment by rgm-22** [comment]
Hi @olokobayusuf,

Thank you for your answer, but I don't understand why you close the issue.
Yes, I can't update because I have other project constraints, and I need that version (I think it is not so strange 😅).

Anyway, for another project, we just successfully installed NatCoder after updating the version (thank you again).
And now, I want to use NatML using my file model in ONNX format.

I guess I have to use "MLModelData.FromFile", but I'm not sure, and I don't know how to continue because your documentation, in my opinion, is very poor: you don't provide too many examples (please take this as a constructive comment 😅).

Thank you again!

**Comment by olokobayusuf** [comment]
> Thank you for your answer, but I don't understand why you close the issue.
Yes, I can't update because I have other project constraints, and I need that version (I think it is not so strange 😅).

I figured you might have had a reason to stay with Unity 2019, but we specifically require Unity 2021.2+. This is mentioned in both [the README](https://github.com/natmlx/NatCorder#requirements) and [the docs](https://docs.natml.ai/natcorder/preliminaries/requirements). So if you're using an older version of Unity, you won't be able to use NatCorder.

> I guess I have to use "MLModelData.FromFile", but I'm not sure, and I don't know how to continue because your documentation, in my opinion, is very poor: I think you don't provide too many examples (please take this as a constructive comment 😅).

Looks like you found [the docs on the topic](https://docs.natml.ai/natml/workflows/models#using-model-files). You can upload your model to NatML Hub, and Hub will convert your model to different formats for use across all the platforms we support.

**Comment by rgm-22** [comment]
Thank you, @olokobayusuf!

Last question 😅:

How should I proceed to record videos without watermarks and resolutions with values greater than 480 pixels?

Thank you again!

**Comment by rgm-22** [comment]
Plan upgraded to "Cloud" 👍.

It works like a charm!

Thanks!

**Comment by olokobayusuf** [comment]
@rgm-22 yup, you'll need to upgrade (which it looks like you did). Also, I recommend using [VideoKit](https://github.com/natmlx/VideoKit) for low-code recording, instead of using NatCorder directly. VideoKit uses NatCorder internally, but makes the process of recording astronomically easier.
